### PR TITLE
ppc64le: initial object files

### PR DESCRIPTION
**Pull request by sm00th**
Add initial set of objectfiles for ppc64le unit tests. Based on
integration test builds against 4.16 kernel.

The list is almost the same as for x86_64 with a couple exceptions:

 - replace-section-reference and special-static-2 are dropped because they patch arch/x86/kvm/x86.c
 - I got 17 changed functions instead of 1 in data-read-mostly:
```
# nm ppc64le/data-read-mostly.OUTPUT.o | grep -i " t "      
0000000000000008 t __dev_change_flags     
0000000000000008 t dev_change_net_namespace                                          
0000000000000008 t dev_change_xdp_fd      
0000000000000008 t dev_get_nest_level     
0000000000000008 t __dev_set_allmulti     
0000000000000008 t __dev_set_promiscuity  
0000000000000008 t netdev_has_any_upper_dev                                          
0000000000000008 t netdev_has_upper_dev   
0000000000000008 t netdev_lower_state_changed                                        
0000000000000008 t netdev_master_upper_dev_get                                       
0000000000000008 t __netdev_update_features                                          
0000000000000008 t __netdev_upper_dev_link                                           
0000000000000008 t netdev_upper_dev_unlink                                           
0000000000000008 t __netif_receive_skb_core                                          
0000000000000008 t register_netdevice     
0000000000000008 t rollback_registered_many                                          
0000000000000008 t unregister_netdevice_queue                                        
```
 - same thing happened with warn-detect so in this PR both ORIG and PATCHED.FAIL don't differ at all, which is different from x86_64.

### CODE REVIEW

**Comment by jpoimboe** [comment]
This is great!  A few things:
- I think warn-detect should be reverted to its original state, such that it fails for now.  This reflects the fact that ppc64le is currently missing WARN macro detection.
- In general, to handle cases like this, would it make sense to add '-k' to MAKEFLAGS, so that *all* tests get run, even if some of them fail?
- Eventually we need to get cross-compilation support for kpatch-build/create-diff-object.  Then we'll be able to run these tests in Travis.

**Comment by jpoimboe** [comment]
> Eventually we need to get cross-compilation support for kpatch-build/create-diff-object. Then we'll be able to run these tests in Travis.

Or in the meantime I wonder if it makes sense to use CentOS CI, since they have ppc64le VMs available?

**Comment by jpoimboe** [comment]
> I think warn-detect should be reverted to its original state, such that it fails for now. This reflects the fact that ppc64le is currently missing WARN macro detection.
> In general, to handle cases like this, would it make sense to add '-k' to MAKEFLAGS, so that all tests get run, even if some of them fail?

Or, instead of having a test which always fails, just remove the '-FAIL' from the file name.  Then we have the object ready, which we can rename to '-FAIL' later once we have proper WARN macro detection.

**Comment by sm00th** [comment]
> Or in the meantime I wonder if it makes sense to use CentOS CI, since they have ppc64le VMs available?

CentosCI seems to be more flexible and offers more resources so I think ultimately kpatch would have to move there at some point, especially if we want to run integration tests automatically as well. However unfortunately setting it up is not as straightforward. I'll look into it though.

> Or, instead of having a test which always fails, just remove the '-FAIL' from the file name. Then we have the object ready, which we can rename to '-FAIL' later once we have proper WARN macro detection.

The problem with this is remembering to switch it back, so the -k approach might be better.

**Comment by sm00th** [comment]
> I think warn-detect should be reverted to its original state, such that it fails for now. This reflects the fact that ppc64le is currently missing WARN macro detection.

Does this also mean that number of changed functions in data-read-mostly should be 1 and we should fail that test as well?

**Comment by jpoimboe** [comment]
I think it's ok for those tests to falsely pass for now, because we should notice that they will start breaking once we add ppc64le WARN detection support.

**Comment by sm00th** [comment]
v2:
 - proper warn-detect that currently doesn't fail
 - added a note about this to commit message

**Pull request merged**
