### PR TITLE
ppc64le: add object files with powerpc cpu feature relocations

### PR DESCRIPTION
**Pull request by joe-lawrence**
PowerPC implements alternative instructions via __ftr_fixup and _ftr_alt* sections.  Add sample object files that contain these sections, create-diff-object should skip rela managling for associated symbols.

### CODE REVIEW

**Comment by joe-lawrence** [comment]
This is for corresponding kpatch-build MR dynup/kpatch#1349 

Here are the interesting sections in these objs:
```
$ readelf --wide --sections ppc64le/ppc64le-ftr-fixup.ORIG.o | grep ftr
  [973] __ftr_alt_97      PROGBITS        0000000000000000 0228f4 000010 00   A  0   0  4
  [974] __ftr_fixup       PROGBITS        0000000000000000 022908 0000c0 00   A  0   0  8
  [975] .rela__ftr_fixup  RELA            0000000000000000 04fce8 000180 18   I 1514 974  8
```

**Comment by jpoimboe** [comment]
Should the commit log show how the objects were made? Also maybe add a .test which does assert_num_funcs?

**Comment by joe-lawrence** [comment]
> Should the commit log show how the objects were made? Also maybe add a .test which does assert_num_funcs?

I'll need to track down which integration test I stole these from :)  And yea, actually adding the .test would be good.

**Comment by joe-lawrence** [comment]
v2: update the commit msg with mention of data-read-mostly.patch and inline the patch that generates these object files
v3: as usual, previous step forgot to `git add` a new file (the .test)

**Review by jpoimboe — APPROVED** [review]

**Pull request merged**
