### PR TITLE
ensure that ignored section symbols are included

### PR DESCRIPTION
**Pull request by joe-lawrence**
kpatch issue #928 noticed that kpatch_mark_ignored_sections() includes a
.rodata.str1.1 section but does not include its section symbol, leading
to a potential segmentation fault after kpatch_elf_teardown().

This issue was reproduced with the following out-of-tree module:

MODULE_DESCRIPTION("testmod_MACROS_FUN002");
MODULE_LICENSE("GPL");

int test_funb(int x,int y)
{
        printk("testEL_HOTPATCH_MACROS_FUN.002 test_funb\n");
        int z=0;
        z= x+y;
        return z;
}
EXPORT_SYMBOL(test_funb);

int __init test_funa(void)
{
        printk("testEL_HOTPATCH_MACROS_FUN.002 test_funa\n");
        int a = 5,b = 3;
        int c = 0;
        c = test_funb(a,b);
        return c;
}
EXPORT_SYMBOL(test_funa);

static int testmod_MACROS_FUN002_init(void)
{
        printk("testmod_MACROS_FUN002_init\n");
        return 0;
}
static void testmod_MACROS_FUN002_exit(void)
{
        printk("testmod_MACROS_FUN002_exit\n");
}

module_init(testmod_MACROS_FUN002_init);
module_exit(testmod_MACROS_FUN002_exit);

and the following patch:

--- testmod.c   2019-02-14 19:55:13.085728341 +0000
+++ testmod.c.new       2018-11-05 08:04:14.000000000 +0000
@@ -7,7 +7,7 @@

 int test_funb(int x,int y)
 {
-       printk("testEL_HOTPATCH_MACROS_FUN.002 test_funb\n");
+       printk("testEL_HOTPATCH_MACROS_FUN.002 test_funb(hotpatch)\n");
        int z=0;
        z= x+y;
        return z;
@@ -23,12 +23,15 @@
        return c;
 }
 EXPORT_SYMBOL(test_funa);
+#include "kpatch-macros.h"
+KPATCH_IGNORE_SECTION(".init.text");

 static int testmod_MACROS_FUN002_init(void)
 {
         printk("testmod_MACROS_FUN002_init\n");
         return 0;
 }
+
 static void testmod_MACROS_FUN002_exit(void)
 {
         printk("testmod_MACROS_FUN002_exit\n");

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>

### CODE REVIEW

**Comment by jpoimboe** [comment]
Isn't this test supposed to cause a seg fault with current code?  It seems to work fine for me.

**Comment by joe-lawrence** [comment]
> Isn't this test supposed to cause a seg fault with current code? It seems to work fine for me.

Interesting.  Since this repro'd for me on x86 but not ppc64le and not at all for @sm00th, I'll double check the object files and the out-of-tree module on my side.

**Comment by joe-lawrence** [comment]
The segfault is lost when stripping the objects, a requirement from the Makefile's `check_stripped()` :
```
[ ... kpatch-build ... ]

% /root/kpatch/kpatch-build/create-diff-object \
    /root/.kpatch/tmp/orig/testmod.o \
    /root/.kpatch/tmp/patched/testmod.o \
    testmod \
    /root/.kpatch/tmp/module/testmod.symtab \
    /root/.kpatch/tmp/Module.symvers livepatch_testmod testmod.o
testmod.o: ignoring section: .init.text
testmod.o: changed function: test_funb
Segmentation fault (core dumped)

% strip --strip-debug --keep-file-symbols \
    ~/.kpatch/tmp/patched/testmod.o -o ~/.kpatch/tmp/patched/testmod-stripped.o
% strip --strip-debug --keep-file-symbols \
    ~/.kpatch/tmp/orig/testmod.o -o ~/.kpatch/tmp/orig/testmod-stripped.o

% /root/kpatch/kpatch-build/create-diff-object \
    /root/.kpatch/tmp/orig/testmod-stripped.o \
    /root/.kpatch/tmp/patched/testmod-stripped.o \
    testmod \
    /root/.kpatch/tmp/module/testmod.symtab \
    /root/.kpatch/tmp/Module.symvers \
    livepatch_testmod testmod.o
testmod-stripped.o: ignoring section: .init.text
testmod-stripped.o: changed function: test_funb
```
Then I ran create-diff-object in gdb, and to see which section we were segfaulting on:
```
(gdb) p sec->name
$2 = 0x7ffff7fde7c5 ".rela.debug_info"
```
Ah, so yeah, I'm stripping the very section that causes the segfault.

**Comment by sm00th** [comment]
Right. I think the check should stay. The easiest way to fix this case I see is to add another make target for non-stripped objfiles. So the names would be something like testname.ORIG.NOSTRIP.o and testname.PATCHED.NOSTRIP.o. This makes exception cases immediately visible during review and we can ask for justification.

Thoughts?

**Comment by joe-lawrence** [comment]
> Right. I think the check should stay. The easiest way to fix this case I see is to add another make target for non-stripped objfiles. So the names would be something like testname.ORIG.NOSTRIP.o and testname.PATCHED.NOSTRIP.o. This makes exception cases immediately visible during review and we can ask for justification.
> 
> Thoughts?

Could the existing targets live with testname.NOSTRIP.ORIG.o and then we skip the strip check for filenames containing "NOSTRIP" ?   ie...

```
 define check_all =
-       $(call check_stripped,$(1))
+       $(if $(findstring NOSTRIP,$(1)), , $(call check_stripped,$(1)))
 endef
```
You'll still have a "NOSTRIP" filename string to flag during review, but get to keep all the existing rules.

**Comment by sm00th** [comment]
Oh yeah, that'll be much better. But apart from implementation would all of us agree to this approach?

**Comment by joe-lawrence** [comment]
Works for me.  I guess the alternatives would be dropping this particular test or the stripped test.  Since an exception is fairly easy and non-invasive, my vote would be to handle both stripped and non-stripped object files.

**Comment by jpoimboe** [comment]
Sounds good to me.

**Comment by joe-lawrence** [comment]
If the above change to `check_all` is what we're going with, I can open a separate PR and test since I've got the non-stripped object files in front of me.  Whatever is easier for you, @sm00th.

**Comment by sm00th** [comment]
You can update this PR to include NOSTRIP versions and then put the makefile changes in a separate commit in the corresponding dynup/kpatch PR after we merge this one.

**Comment by joe-lawrence** [comment]
v2: updated the object files with their non-stripped versions, renamed to include "NOSTRIP".

Before the related kpatch fix:
```
% make -s unit
BUILD oot-issue-928.NOSTRIP
/bin/sh: line 2:  8230 Segmentation fault      PARA_STRUCT_SIZE=16 EX_STRUCT_SIZE=12 BUG_STRUCT_SIZE=12 ALT_STRUCT_SIZE=13 JUMP_STRUCT_SIZE=24 /root/github-kpatch/kpatch-build/create-diff-object oot-issue-928.NOSTRIP.ORIG.o oot-issue-928.NOSTRIP.PATCHED.o vmlinux oot-issue-928.NOSTRIP.symtab /dev/null test_oot-issue-928.NOSTRIP oot-issue-928.NOSTRIP.OUTPUT.o > /dev/null
make[2]: *** [oot-issue-928.NOSTRIP.OUTPUT.o] Error 139
make[1]: *** [all] Error 2
make: *** [unit] Error 2
```
And then after:
```
% make -s unit
BUILD oot-issue-928.NOSTRIP
BUILD gcc-static-local-var-5
BUILD function-ptr-new
BUILD warn-detect-FAIL
BUILD data-read-mostly
BUILD this_ip
BUILD meminfo-init-FAIL
BUILD cold-del-sub
BUILD cold-change-sub
BUILD gcc-constprop
BUILD gcc-constprop-cold
BUILD mrecord-mcount
BUILD meminfo-init2-FAIL
BUILD bug-table-section
BUILD special-static
BUILD fixup-section
BUILD convert-global-local
BUILD cold-change-parent
BUILD meminfo-string
BUILD data-new
BUILD gcc-static-local-var-3
BUILD cold-add2
BUILD special-static-2
BUILD tracepoints-section
BUILD cold-add
BUILD new-function
BUILD smp-locks-section
BUILD replace-section-references
TEST replace-section-references
TEST gcc-constprop
TEST special-static-2
TEST meminfo-string
TEST data-read-mostly
TEST convert-global-local
TEST cold-del-sub
TEST gcc-constprop-cold
TEST gcc-static-local-var-5
TEST mrecord-mcount
TEST function-ptr-new
TEST bug-table-section
TEST fixup-section
TEST this_ip
TEST cold-change-parent
TEST special-static
TEST data-new
TEST gcc-static-local-var-3
TEST cold-add2
TEST cold-change-sub
TEST tracepoints-section
TEST cold-add
TEST new-function
TEST smp-locks-section
```

**Pull request merged**
