### PR TITLE
gcc-constprop update to gcc8 version

### PR DESCRIPTION
**Pull request by sm00th**
Replace gcc-constprop objects with gcc8 versions that include *.cold.*
symbols. See https://github.com/dynup/kpatch/pull/856 for more info.

Signed-off-by: Artem Savkov <asavkov@redhat.com>

---

This commit just replaces old constprop objects with new ones since they now test both cases. We might add a separate "gcc-cold" testcase to make it clearer that we actually test 2 different things. What do you think?

### CODE REVIEW

**Comment by jpoimboe** [comment]
Why does it have three functions now instead of one?

Also (and I realize I'm a bit late with this idea), what do you think about putting the patch in the commit log so we can rebuild it easier for cases like this?

**Comment by sm00th** [comment]
> Why does it have three functions now instead of one?

My tunnel vision was focused on another issue and I missed this one. A ".cold." symbol for one of the functions wasn't properly correlated. I've added a commit fixing this to the other PR and changed the .test file back to it's original state.

> Also (and I realize I'm a bit late with this idea), what do you think about putting the patch in the commit log so we can rebuild it easier for cases like this?

I was thinking of a place where we can put this and commitmsg is suitable as long as we keep the patches small. Changed the commit message to include the patch.

**Comment by jpoimboe** [comment]
> This commit just replaces old constprop objects with new ones since they now test both cases. We might add a separate "gcc-cold" testcase to make it clearer that we actually test 2 different things. What do you think?

Yeah, I would vote to instead put it in a new gcc-constprop-cold test case, if possible.  Doesn't hurt to have more tests.

Also, a similar ppc64le test would be good.

**Comment by sm00th** [comment]
> Also, a similar ppc64le test would be good.

Tried building this patch on ppc64le and gcc8.1 did no optimizations there, so we'll have to find another way to reproduce it there.

v2:
  - separate gcc-constprop-cold case

**Pull request merged**
