### PR TITLE
all: debug and line detection fixes for btrfs code

### PR DESCRIPTION
**Pull request by jpoimboe**
x86 and ppc64le unit tests for https://github.com/dynup/kpatch/pull/1254.  If somebody can point me to a working s390 tree I can try to make unit tests for s390 too.

### CODE REVIEW

**Comment by joe-lawrence** [comment]
Progress on Sumanth's PR had stalled, but it should still work on top of a recent rhel-9 dev install:
https://github.com/sumanthkorikkar/kpatch/tree/s390x-kpatch-support

There is also Erastus's PR that added the original line detection code on top of Sumanth's work:
https://github.com/C-Erastus/kpatch/tree/s390-line-macro

There has been enough kpatch-build and code churn that, much like the arm64 PR, the s390x PR will need some rebasing care in the future.  I also have a half-complete local branch to extend cross-arch unit test for s390x and specifically big-endian.  But I think you'll need a native s390x beaker box to build the kernel anyway, so just run the tests there, too :)

**Comment by jpoimboe** [comment]
v2: add s390 test binaries

**Comment by joe-lawrence** [comment]
Thanks for adding the s390x files.  Any chance you could add the nm output for the expected assert function?  (I think all the s390x .test files have them.)  I found the output helpful in cases where the test failed and I have to figure out what's missing/added.

**Comment by jpoimboe** [comment]
Good idea, will do

**Comment by jpoimboe** [comment]
v2:
- add 'nm' output to the tests

BTW, I can't guarantee the s390 `assert_num_funcs()` will work since I guess it depends on whether the retpoline thunks get included in the output object.  But that can be a trivial fix later, if needed.

At some point we might want to make `assert_num_funcs()` smarter somehow, so that instead of checking 'nm' it actually determines the patched function list.

**Comment by joe-lawrence** [comment]
> v2:
> 
>     * add 'nm' output to the tests
> 
> 
> BTW, I can't guarantee the s390 `assert_num_funcs()` will work since I guess it depends on whether the retpoline thunks get included in the output object. But that can be a trivial fix later, if needed.
> 

Is this referring to using EXPOLINE_EXTERN?  Worse case scenario, we could filter then from the list.

> At some point we might want to make `assert_num_funcs()` smarter somehow, so that instead of checking 'nm' it actually determines the patched function list.

A while back, Arnaldo [enhanced pahole](https://git.kernel.org/pub/scm/devel/pahole/pahole.git/commit/?id=a83313fb22520d8db05ab3003368192551e980d7) with the ability to pass in a binary blob on stdin, so we may be able to extract the kpatch list from the ELF file and then parse the pretty print.  (Unless there is a simpler way.)


Since the corresponding kpatch PR saw a few more revisions, does this PR have everything you'd like?  If so, I'll approve and we can merge so the kpatch PR can bump the submodule reference forward.

**Comment by jpoimboe** [comment]
> Is this referring to using EXPOLINE_EXTERN? Worse case scenario, we could filter then from the list.

Yes

> A while back, Arnaldo [enhanced pahole](https://git.kernel.org/pub/scm/devel/pahole/pahole.git/commit/?id=a83313fb22520d8db05ab3003368192551e980d7) with the ability to pass in a binary blob on stdin, so we may be able to extract the kpatch list from the ELF file and then parse the pretty print. (Unless there is a simpler way.)

Wow, that's a really nice pahole feature.  Maybe we could do something like that.

> Since the corresponding kpatch PR saw a few more revisions, does this PR have everything you'd like? If so, I'll approve and we can merge so the kpatch PR can bump the submodule reference forward.

Yeah, this PR is still valid.  If it looks ok, feel free to merge it and then I'll bump the other PR.

**Review by joe-lawrence — APPROVED** [review]

**Review by sm00th — APPROVED** [review]

**Pull request merged**
